version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REGISTRY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - export site_app=${REGISTRY_URI}site
  build:
    commands:
      - ./build.sh
